name: Telegram Bot
on:
  schedule:
    - cron: '*/5 * * * *' # ၅ မိနစ်တိုင်း အလုပ်လုပ်မယ်
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with: {python-version: '3.9'}
      - name: Install dependencies
        run: |
          sudo apt-get install ffmpeg
          pip install python-telegram-bot yt-dlp gTTS
      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python main.py
